server:
  port: 80
spring:
  application:
    name: cloud-order-service
eureka:
  client:
    #是否注册
    register-with-eureka: true
    #是否抓取注册信息 默认为true,单点无所谓，但是集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    #注册地址
    service-url:
      #单机版
      # defaultZone: http://localhost:7001/eureka
      #集群版
      defaultZone: http://zpc:123456@eureka7001.com:7001/eureka,http://zpc:123456@eureka7002.com:7002/eureka
  instance:
    instance-id: order80
    prefer-ip-address: true #访问路径显示ip
    #eureka客户端向服务器发送心跳的时间间隔（单位：秒 默认30秒）
    lease-expiration-duration-in-seconds: 1
    #eureka服务端在收到最后一次心跳后等待时间上线（单位：秒 默认90秒） 超时剔除服务
    lease-renewal-interval-in-seconds: 2