server:
  port: 80

spring:
  application:
    name: cloud-feign-hysteix-order-service

eureka:
  client:
    #是否注册
    register-with-eureka: true
    #是否抓取注册信息 默认为true,单点无所谓，但是集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    #注册地址
    service-url:
      #服务端配置了账户和密码
      defaultZone: http://zpc:123456@eureka7001.com:7001/eureka,http://zpc:123456@eureka7002.com:7002/eureka
  instance:
    instance-id: hysteix-order80
    prefer-ip-address: true #访问路径显示ip
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 2

feign:
  hystrix:
    enabled: true #服务降级用到的
