server:
  port: 8663
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中西动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #路由的ID没有固定，配合服务名称
#          uri: http://localhost:8001  #匹配服务i的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**  #断言，路径和匹配的进行路由

        - id: payment_routh2 #路由的ID没有固定，配合服务名称
#          uri: http://localhost:8001 #匹配服务i的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址   lb是Loaded RoutePredicateFactory
          predicates:
            - Path=/payment/lb/**  #断言，路径和匹配的进行路由


#eureka
eureka:
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://zpc:123456@eureka7001.com:7001/eureka,http://zpc:123456@eureka7002.com:7002/eureka
  instance:
    hostname: cloud-gateway-server
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 50
