server:
  port: 8007

spring:
  application:
    name: cloud-provider-hystrix-payment    #项目名称

#eureka配置
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://zpc:123456@eureka7001.com:7001/eureka,http://zpc:123456@eureka7002.com:7002/eureka
  #修改主机名称
  instance:
    instance-id: hystrix-payment8007
    prefer-ip-address: true   #访问路径可以显示ip地址
    #eureka客户端向服务器发送心跳的时间间隔（单位：秒 默认30秒）
    lease-expiration-duration-in-seconds: 50
    #eureka服务端在收到最后一次心跳后等待时间上线（单位：秒 默认90秒） 超时剔除服务
    lease-renewal-interval-in-seconds: 2
